### ISSUE TITLE
Question on Cartesian Coriolis term for example of dellasantina_arm.m

### ISSUE THREAD

**Issue by pllee4** [BJCaasenbrood/SorotokiCode#16]
Hi @BJCaasenbrood , I am looking at the controller code for dellasantina_arm.m and try to understand them.
As cited in the paper [[118]](https://journals.sagepub.com/doi/epub/10.1177/0278364919897292)

In dellasantina_arm.m, under `function tau = Control(shp, Xd)`

I am expecting
```
eta = lam*(J*Mi*C - dJ);
```

instead of
```
eta = lam*(J*Mi*C);
```

following both the paper [[118]](https://journals.sagepub.com/doi/epub/10.1177/0278364919897292) 

![image](https://github.com/BJCaasenbrood/SorotokiCode/assets/42335542/64d1dbd2-455d-4ca2-9f64-8fb21e3d1cf8)

and your [paper](https://github.com/BJCaasenbrood/SorotokiCode/blob/master/paper.pdf) as well 

![image](https://github.com/BJCaasenbrood/SorotokiCode/assets/42335542/d90b3a54-b287-486f-a964-cb3b818d8ac6)

May I know is there any specific reason for the code to ignore `dJ`?

I realized the result for the example would not be similar if `dJ` is included, unless additional change to `Dc`
such as `Dc = 0.7 * Kc;`

**Comment by BJCaasenbrood** [comment]
He @pllee4, you are right, the time derivative of the Jacobian should be included in the controller, an oversight on my end.

Do the state trajectories change significantly?

**Comment by BJCaasenbrood** [comment]
He @pllee4, you are right, the time derivative of the Jacobian should be included in the controller, an oversight on my end.

Do the state trajectories change significantly? 

Also, having `Dc = 0.7 Kc` is rather high, I have to look into that.

**Comment by pllee4** [comment]
>Do the state trajectories change significantly?

I am not sure what's wrong, but the change is significant, it would become this immediately with only the change of adding `dJ`

![image](https://github.com/BJCaasenbrood/SorotokiCode/assets/42335542/bba2d382-d358-4ab0-aed6-0e70d51a2174)

**Comment by BJCaasenbrood** [comment]
@pllee4 I've experimented a bit, and think there is a quirk with `dJ` when it is initialized. With these changes:

```matlab
dJ = shp.system.dJacobian(4:6,:,end) * smoothstep(2*t);
Kc = 1e-3 * smoothstep(15*t);
Dc = 0.1 * Kc;
```

I do get a stable simulation. It seems `dJ` is poorly estimated with `dq` is close to zero, which it is initialized. I'll investigate a bit more in the upcoming days.

**Comment by pllee4** [comment]
>@pllee4 I've experimented a bit, and think there is a quirk with `dJ` when it is initialized

Thanks @BJCaasenbrood for the checking.

Ya, I did able to get the same stable simulation after following the suggested change.

I was also trying to read and understand the `function g = admap(x)` and `function Ad = Admap(R,p)` since they are involved in computation of `dJdt`

Do you have any reference for the equation to compute `dJdt`?

I could be wrong but initially I thought there could be typo for `Ad(4:6,1:3) = S * R;`, like should it be `Ad(1:3,4:6) = S * R;` under `computeFrameChangeFast.m`
when I saw from some [resource](https://arxiv.org/pdf/1812.01537.pdf)
![image](https://github.com/BJCaasenbrood/SorotokiCode/assets/42335542/15d000b5-52a4-48f3-81c0-33394db58339)

But I haven't fully followed all the computation, would be good if you don't mind to share the references / paper for the computation under `computeFrameChangeFast`, still trying to learn 😅

**Comment by BJCaasenbrood** [comment]
So `Admap` and `admap` are the adjoint maps, where the former is responsible for transforming velocities and/or force from one frame into another. As such, it depends on how we define the mapping from $\mathrm{se}(3)$ (i.e. Lie algebra) to $\mathbb{R}^6$, called the isomorphism denoted often by the operator $(\cdot)^\vee$. 

In the work of Sola, they define velocities as $\eta = (v, \omega)^\top$ with $v$ and $\omega$ the linear and rotational velocity components, respectively, whereas we follow the convention $\eta = (\omega, v)^\top$. Similarly, we follow the convention for wrenches as $\mathcal{F} = (m,n)^\top$ with $m$ and $n$ being moments and forces, respectively.

Therefore, the adjoint mapping will look as follows (as to match our convention):

$$Ad_{g} = \begin{bmatrix} R & 0 \newline [t]_\times R & R \end{bmatrix}$$

This convection is similar to the stellar work of Renda/Boyer et al. [[1]](https://hal.science/hal-02318617/file/Strain_parametrized_Cosserat_soft_robots.pdf) (see Appendix A). It is also the same convention I follows in my PhD thesis [[2]](https://github.com/BJCaasenbrood/thesis). The computation of `dJ` is found in Appendix D.2 of my thesis. I remember seeing a similar expression for it in literature (but no derivation), I'll try to find it...

**Comment by BJCaasenbrood** [comment]
I did notice a term missing the `dJ` in the file `sorotokimodel/mex/forwardkin/computeForwardKinematicsGaussFast`. I've made the following modification:

```matlab
eta = J(:,:,jj+1) * dx;
ad = admap_inline(eta);
% Jt(:,:,jj+1) =  Ad * dBt; % (old)
Jt(:,:,jj+1) = -ad * J(:,:,jj+1) + Ad * dBt; % new
```

You can modify the file yourself, make sure to run `generateMexFKGF` to rebuild the mex file. Although the simulation is now stable even without the `smoothstep` in `dJ`, something still feels off.

**Comment by BJCaasenbrood** [comment]
I've pushed the changes in the following commit: https://github.com/BJCaasenbrood/SorotokiModel/commit/5ce63224e9c5432c0deefbc5b3894be2db2dbc9c

**Comment by pllee4** [comment]
> So `Admap` and `admap` are the adjoint maps, where the former is responsible for transforming velocities and/or force from one frame into another. As such, it depends on how we define the mapping from se(3) (i.e. Lie algebra) to R6, called the isomorphism denoted often by the operator (⋅)∨.
> 
> In the work of Sola, they define velocities as η=(v,ω)⊤ with v and ω the linear and rotational velocity components, respectively, whereas we follow the convention η=(ω,v)⊤. Similarly, we follow the convention for wrenches as F=(m,n)⊤ with m and n being moments and forces, respectively.
> 
> Therefore, the adjoint mapping will look as follows (as to match our convention):
> 
> Adg=[R0[t]×RR]
> 
> This convection is similar to the stellar work of Renda/Boyer et al. [[1]](https://hal.science/hal-02318617/file/Strain_parametrized_Cosserat_soft_robots.pdf) (see Appendix A). It is also the same convention I follows in my PhD thesis [[2]](https://github.com/BJCaasenbrood/thesis). The computation of `dJ` is found in Appendix D.2 of my thesis. I remember seeing a similar expression for it in literature (but no derivation), I'll try to find it...

Thanks for the sharing and explanation, would check it out! :smile:

**Comment by pllee4** [comment]
> I did notice a term missing the `dJ` in the file `sorotokimodel/mex/forwardkin/computeForwardKinematicsGaussFast`. I've made the following modification:
> 
> ```matlab
> eta = J(:,:,jj+1) * dx;
> ad = admap_inline(eta);
> % Jt(:,:,jj+1) =  Ad * dBt; % (old)
> Jt(:,:,jj+1) = -ad * J(:,:,jj+1) + Ad * dBt; % new
> ```
> 
> You can modify the file yourself, make sure to run `generateMexFKGF` to rebuild the mex file. Although the simulation is now stable even without the `smoothstep` in `dJ`, something still feels off.
> 
> edit: slightly increasing the contact damping to `Dc = 0.2 * Kc` makes a lot of difference.
> 
> 2nd edit: I've changed the `Kc` and `Dc` to the values used in the paper from Della Santina et al. (see below), and removed the `smoothstep` in the time-derivative of the Jacobian. The simulation are now stable. (note that Sorotoki uses `mm` instead of `m` hence the factor `1e-3`). I do still need the `smoothstep` for `Kc`, but it is only zero for 1/100 of a second.
> 
> ```matlab
> Kc = 0.825 * 1e-3 * smoothstep(100*t);
> Dc = 0.25 * 1e-3;
> ```

It becomes stable now, thanks!

**Comment by BJCaasenbrood** [comment]
Issue resolved with https://github.com/BJCaasenbrood/SorotokiModel/commit/5ce63224e9c5432c0deefbc5b3894be2db2dbc9c
