### ISSUE TITLE
Errors and solutions for "examples"

### ISSUE THREAD

**Issue by Beta-y** [BJCaasenbrood/SorotokiCode#19]
Hi @BJCaasenbrood, thank you for your excellent work!

There are several errors when I tested the provided examples, and I tried to fix them all. Here are the details:

> Error 0: 
> Unrecognized field name "V"
> 
> Influenced examples by Error 0:
> fem_eigen_comp
> 
> Fix Error 0:
> Line 18 of examples\fem\fem_eigen_comp.m: `fem.solver.sol.x = fem.solver.pod.V(:,ii) * 250; `
> should be: `fem.solver.sol.x = fem.solver.sol.pod.V(:,ii) * 250;`

> Error 1：
> Incorrect size for expression 'Dvec': expected [6x6x:?x:?] but found [5x1].
> Error in computeLagrangianGaussFast_mex
> 
> Influenced examples by Error 1:
> dellasantina_arm
> softhand
> backbone_test
> shapes_octoarm
> shapes_reconstruct
> shapes_threebellow_robotmanipulator
> 
> Fix Error 1:
> I found it in computeLagrangianGaussFast.h that the type of "Dvec" is declared as "const emxArray_real_T *", but the "generateMexCLGF.m" uses "coder.typeof(10,[5,1])" for "Dvec", which means it's correct. So I ran "generateMexCLGF.m" again, got the correct mex-file, and fixed this problem finally.

> Error 2:
> Error using  * 
> Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of rows in the second matrix. To operate on each element of the matrix individually, use TIMES (.*) for elementwise multiplication.
> 
> Influenced examples by Error 2:
> suzumori_gripper
> jacobian_control_shapes
> shapes_backbone_IK_test
> 
> Fix Error 2:
> Line 76 of tubeplot.m:  `Fx = (1+1/8*sin(2*X).^2)*cos(X)`
> should be:   `Fx = (1+1/8*sin(2*X).^2).*cos(X)`

> Warning 1 (when running dellasatina_arm):
> Warning: Name is nonexistent or not a directory: PATH\mpi-packages\sorotokicode\+preset\+shapes\assets
> 
> Fix Warning 1:
> Line 49 of katzschmann.m: `functionPath = fullfile(currentDir,'assets');`
> should be: `functionPath = fullfile(fileparts(currentDir),'assets');`

Hope them can be merged into next version. Thank you again for your great work!

**Comment by BJCaasenbrood** [comment]
Addressed error 0 in following commit: https://github.com/BJCaasenbrood/SorotokiCode/commit/0e4fa5c71375389c1aba14a43dc1bc09d3ab14d1

Running `fem_eigen_comp` should give the following result:

![image](https://github.com/BJCaasenbrood/SorotokiCode/assets/36262141/f22b628d-acc9-4748-85d5-28726b806db5)

**Comment by BJCaasenbrood** [comment]
Addressed error 2 in following commit: https://github.com/BJCaasenbrood/SorotokiModel/commit/e8a359772debdacda54da7c8bc8385024732d9a9

**Note**: `Shapes.show` now uses the `rtubeplot` function instead of `tubeplot`. This will like change in the future, giving users to option to choose between the two.

**Comment by Beta-y** [comment]
Thank you for your kind help and sugesstions! I used `sorotoki update` and found another error in `checkSoroPackages`(line 19):

> Unable to convert '24-Apr-2024 15:59:11' to datetime using the format 'dd-MMM-yyyy HH:mm:ss'.
If the date/time text contains day, month, or time zone names in a language foreign to the
'zh_CN' locale, those might not be recognized. You can specify a different locale using the
'Locale' parameter.

It seems to be a language setting problem. I replaced `installDate = datetime(mpiDates{I}, 'InputFormat', 'dd-MMM-yyyy HH:mm:ss')` into `installDate = datetime(mpiDates{I}, 'InputFormat', 'dd-MMM-yyyy HH:mm:ss','Locale','en_US')` and it works successfully.

I'll keep on checking your commit. Thanks a lot~

**Comment by Beta-y** [comment]
> He @Beta-y, thanks a lot of the debugging. I'll get on them right away. As for error 1, yesterday I've added the ability to add viscous drag. If you have the latest version of Sorotoki you can call:
> 
> ```matlab
> sorotoki update
> ```
> 
> Also make sure to build the code using `sorotoki build`. I did hear from a user, the build didn't work for him (not sure why). If you have this issue as well, please report back to me. If it doesn't work, you can run `SorotokiCode/lib/sorotokimodel/mex/lagrangian/generateMexCLGF.m`. Make sure you are in the folder `SorotokiCode/lib/sorotokimodel/mex/lagrangian/`.

`sorotoki build` does not work for me, as well. I think there is something wrong in `@sorotoki\private\buildSorotokiMex.m` (Line 191) about buildLagrangian. The `coder.typeof` of `Dvec` should be `coder.typeof(10,[5,1])` instead of `coder.typeof(10,[6,6,inf,inf])`.

**Comment by BJCaasenbrood** [comment]
> > He @Beta-y, thanks a lot of the debugging. I'll get on them right away. As for error 1, yesterday I've added the ability to add viscous drag. If you have the latest version of Sorotoki you can call:
> > ```matlab
> > sorotoki update
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also make sure to build the code using `sorotoki build`. I did hear from a user, the build didn't work for him (not sure why). If you have this issue as well, please report back to me. If it doesn't work, you can run `SorotokiCode/lib/sorotokimodel/mex/lagrangian/generateMexCLGF.m`. Make sure you are in the folder `SorotokiCode/lib/sorotokimodel/mex/lagrangian/`.
> 
> `sorotoki build` does not work for me, as well. I think there is something wrong in `@sorotoki\private\buildSorotokiMex.m` (Line 191) about buildLagrangian. The `coder.typeof` of `Dvec` should be `coder.typeof(10,[5,1])` instead of `coder.typeof(10,[6,6,inf,inf])`.

It seems you are still running an older version I think, this change is implemented in a commit yesterday. You can see here: https://github.com/BJCaasenbrood/SorotokiModel/blob/master/mex/lagrangian/generateMexCLGF.m

**Comment by Beta-y** [comment]
> > > He @Beta-y, thanks a lot of the debugging. I'll get on them right away. As for error 1, yesterday I've added the ability to add viscous drag. If you have the latest version of Sorotoki you can call:
> > > ```matlab
> > > sorotoki update
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also make sure to build the code using `sorotoki build`. I did hear from a user, the build didn't work for him (not sure why). If you have this issue as well, please report back to me. If it doesn't work, you can run `SorotokiCode/lib/sorotokimodel/mex/lagrangian/generateMexCLGF.m`. Make sure you are in the folder `SorotokiCode/lib/sorotokimodel/mex/lagrangian/`.
> > 
> > 
> > `sorotoki build` does not work for me, as well. I think there is something wrong in `@sorotoki\private\buildSorotokiMex.m` (Line 191) about buildLagrangian. The `coder.typeof` of `Dvec` should be `coder.typeof(10,[5,1])` instead of `coder.typeof(10,[6,6,inf,inf])`.
> 
> It seems you are still running an older version I think, this change is implemented in a commit yesterday. You can see here: https://github.com/BJCaasenbrood/SorotokiModel/blob/master/mex/lagrangian/generateMexCLGF.m

It is kind of strange that neither update or re-install gives the correct latest commit. I've tried to uninstall sorotokicode, and reinstall using `mpi install sorotokicode --all-paths` (`mpi install sorotokicode -u https://github.com/BJCaasenbrood/SorotokiCode.git --all-paths` as well). Calling `sorotoki update` shows the following:

> lastestDate = 
> 
>   datetime
> 
>    19-Apr-2024 20:04:25
> 
> 
> installDate = 
> 
>   datetime
> 
>    24-Apr-2024 20:50:48
> 
> ....
> 
> Sorotoki libraries found on MPI are up-to-date

It seems the package is not latest. Let me check this tommorrow! lol~ Thanks you a lot for your kind help :P

**Comment by Beta-y** [comment]
> > > > He @Beta-y, thanks a lot of the debugging. I'll get on them right away. As for error 1, yesterday I've added the ability to add viscous drag. If you have the latest version of Sorotoki you can call:
> > > > ```matlab
> > > > sorotoki update
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Also make sure to build the code using `sorotoki build`. I did hear from a user, the build didn't work for him (not sure why). If you have this issue as well, please report back to me. If it doesn't work, you can run `SorotokiCode/lib/sorotokimodel/mex/lagrangian/generateMexCLGF.m`. Make sure you are in the folder `SorotokiCode/lib/sorotokimodel/mex/lagrangian/`.
> > > 
> > > 
> > > `sorotoki build` does not work for me, as well. I think there is something wrong in `@sorotoki\private\buildSorotokiMex.m` (Line 191) about buildLagrangian. The `coder.typeof` of `Dvec` should be `coder.typeof(10,[5,1])` instead of `coder.typeof(10,[6,6,inf,inf])`.
> > 
> > 
> > It seems you are still running an older version I think, this change is implemented in a commit yesterday. You can see here: https://github.com/BJCaasenbrood/SorotokiModel/blob/master/mex/lagrangian/generateMexCLGF.m
> 
> It is kind of strange that neither update or re-install gives the correct latest commit. I've tried to uninstall sorotokicode, and reinstall using `mpi install sorotokicode --all-paths` (`mpi install sorotokicode -u https://github.com/BJCaasenbrood/SorotokiCode.git --all-paths` as well). Calling `sorotoki update` shows the following:
> 
> > lastestDate =
> > datetime
> > 19-Apr-2024 20:04:25
> > installDate =
> > datetime
> > 24-Apr-2024 20:50:48
> > ....
> > Sorotoki libraries found on MPI are up-to-date
> 
> It seems the package is not latest. Let me check this tommorrow! lol~ Thanks you a lot for your kind help :P

I noticed that it seems (not sure) that neither `sorotoki install` or `sorotoki update` would update `sorotokicode`, but just repos listed in variable named `soroPackages`.

BTW, there is exactly something wrong in `@sorotoki\private\buildSorotokiMex.m` (Line 191) about buildLagrangian, which is included in `sorotokicode`, and the `coder.typeof` of `Dvec` should be `coder.typeof(10,[5,1])` instead of `coder.typeof(10,[6,6,inf,inf])`. Please refer to [https://github.com/BJCaasenbrood/SorotokiCode/blob/master/%40sorotoki/private/buildSorotokiMex.m](https://github.com/BJCaasenbrood/SorotokiCode/blob/master/%40sorotoki/private/buildSorotokiMex.m)

**Comment by BJCaasenbrood** [comment]
Issue of `sorotoki update` referred to https://github.com/BJCaasenbrood/SorotokiCode/issues/20
