### ISSUE TITLE
several errors when I tested the realtime_example.m,

### ISSUE THREAD

**Issue by lowkey9527** [BJCaasenbrood/SorotokiCode#23]
Hi @BJCaasenbrood, thank you for your excellent work!

There are several errors when I tested the realtime_example.m, and I tried to fix them all. Here are the details:

**wrong use of Control
Cannot create a communication link with the remote server.
Please check the input arguments(ADDRESS and PORT) and
make sure the server is running.
Additional Information: Unable to connect because the target computer actively refused。
[system:10061]
 realtime_example (第 9 行)
brd = Control(usr,ip,pwd,'autoConnect',false,...**

**Comment by BJCaasenbrood** [comment]
@lowkey9527, thanks for all your interest. The `realtime_example.m` is meant to interface with the realtime control platform from Sorotoki -- a Raspberry pi connected to a Festo hardware hat. Information of the platform can be found on: https://ieeexplore.ieee.org/document/9762137/

Without it, the scripts will not work....

**Comment by lowkey9527** [comment]
@BJCaasenbrood Thank you for the reply. I just begin with the soft robots. I am not familiar with the soft robots. But I want to know : Can I just use the sorotoki to simulate the control of soft robots?  (no hardware just MATLAB code)

**Comment by BJCaasenbrood** [comment]
> @BJCaasenbrood Thank you for the reply. I just begin with the soft robots. I am not familiar with the soft robots. But I want to know : Can I just use the sorotoki to simulate the control of soft robots?  (no hardware just MATLAB code)

Sorotoki is a general framework for design, modeling and control. So yes! Absolutely you can use sorotoki to control virtual soft robots.

I'd recommend checking out the examples folder, and running some of these. I'd recommend checking out the `dellasantina_arm.m` and `jacobian_control_shapes.m` scripts.
