### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by martijnschouten** [BJCaasenbrood/SorotokiCode#3]
Hi Brandon,

Great work! Can you maybe add the project to Zenodo or 4TU research data, so that we can cite it using a DOI and long-term access will be guaranteed?

Also if you add a CITATION.cff file a cite this repository as button will pop up in github

**Comment by BJCaasenbrood** [comment]
Dear Martijn,

Sorotoki has (finally) been published in IEEE Access as of this year. The DOI can be found here: [.1109/ACCESS.2024.3357351](https://doi.org/10.1109/ACCESS.2024.3357351)

**Comment by BJCaasenbrood** [comment]
Dear Martijn,

Sorotoki has (finally) been published in IEEE Access as of this year. The DOI can be found here: [.1109/ACCESS.2024.3357351](https://doi.org/10.1109/ACCESS.2024.3357351)
